(define (problem problem-1-hard)
    (:domain domain_one)

    (:objects
        N1 N2 N3 N4 N5 N6 N7 N8 N9 N10 
        N11 N12 N13 N14 N15 N16 N17 N18 N19 N20 
        N21 N22 N23 N24 N25 - node

        Beer Pizza Sushi Burrito Soda Curry Taco 
        Burger Fries Donut - food

        OldMan OldLady Man Woman FishMan Student 
        Chef Gamer Tourist Worker - person

        Scooter Bike - courier
    )

    (:init
        (RoadNetwork N1 N2)
        (RoadNetwork N2 N3)
        (RoadNetwork N3 N4) 
        (RoadNetwork N4 N5)
        (RoadNetwork N5 N6)
        (RoadNetwork N6 N7)
        (RoadNetwork N7 N8)
        (RoadNetwork N8 N9)
        (RoadNetwork N9 N10) 
        (RoadNetwork N10 N11)
        (RoadNetwork N11 N12)
        (RoadNetwork N12 N13)
        (RoadNetwork N13 N14)
        (RoadNetwork N14 N15)
        (RoadNetwork N15 N16)
        (RoadNetwork N16 N17)
        (RoadNetwork N17 N18)
        (RoadNetwork N18 N19)
        (RoadNetwork N19 N20)
        (RoadNetwork N20 N21)
        (RoadNetwork N21 N22)
        (RoadNetwork N22 N23) 
        (RoadNetwork N23 N24)
        (RoadNetwork N24 N25)
        (RoadNetwork N25 N1)
        (RoadNetwork N5 N10)
        (RoadNetwork N10 N15)
        (RoadNetwork N15 N20) 
        (RoadNetwork N20 N25)
        (RoadNetwork N25 N5)
        (Serves Curry N2)
        (Serves Sushi N3)
        (Serves Beer N5) 
        (Serves Soda N7)
        (Serves Burrito N10)
        (Serves Taco N12) 
        (Serves Pizza N15)
        (Serves Burger N18)
        (Serves Fries N22) 
        (Serves Donut N24)
        (Location OldMan N4)
        (Location Man N8)
        (Location OldLady N12) 
        (Location Woman N16)
        (Location FishMan N20)
        (Location Student N6)
        (Location Chef N9)
        (Location Gamer N13)
        (Location Tourist N18)
        (Location Worker N23)
        (Ordered Beer Man)
        (Ordered Curry OldMan)
        (Ordered Pizza Woman)
        (Ordered Sushi OldLady)
        (Ordered Burrito FishMan)
        (Ordered Soda Student)
        (Ordered Taco Chef)
        (Ordered Burger Gamer)
        (Ordered Fries Tourist)
        (Ordered Donut Worker)
        (Location Scooter N1) 
        (Location Bike N25)
    )

    (:goal 
        (and
            (DeliveryMade Beer Man)
            (DeliveryMade Curry OldMan)
            (DeliveryMade Pizza Woman)
            (DeliveryMade Sushi OldLady)
            (DeliveryMade Burrito FishMan)
            (DeliveryMade Soda Student)
            (DeliveryMade Taco Chef)
            (DeliveryMade Burger Gamer)
            (DeliveryMade Fries Tourist)
            (DeliveryMade Donut Worker)
        )
    )
)
